#!/bin/bash

set -euo pipefail

BASE=$(pwd)

eval $(/opt/homebrew/bin/brew shellenv)

mkdir -p ~/.config/fish
ln -sf $BASE/config.fish ~/.config/fish/config.fish
ln -sf $BASE/fish_plugins ~/.config/fish/fish_plugins

if [ ! -f ~/.config.fish.local ]; then
  cat << EOF > ~/.config.fish.local
# Local config
EOF
fi

brew install fish

echo 'Install Fisher (https://github.com/jorgebucaran/fisher)'
fish -c 'curl -sL https://git.io/fisher | source && fisher update'

if [ ! $(grep "fish" /etc/shells) ]; then
  echo $(which fish) | sudo tee -a /etc/shells
fi

# Make fish default shell
chsh -s $(which fish)
