#!/bin/bash

set -euo pipefail

context='[fish]'

log() {
  echo "$context $*"
}

log "start"

base=$(pwd)

mkdir -p ~/.config/fish
ln -sf $base/config.fish ~/.config/fish/config.fish
ln -sf $base/fish_plugins ~/.config/fish/fish_plugins

if [ ! -f ~/.config.fish.local ]; then
  cat << EOF > ~/.config.fish.local
# Local config
EOF
fi

log 'Install Fisher (https://github.com/jorgebucaran/fisher)'
fish -c 'curl -sL https://git.io/fisher | source && fisher update'

if [ ! $(grep "fish" /etc/shells) ]; then
  echo $(which fish) | sudo tee -a /etc/shells
fi

# Make fish default shell
chsh -s $(which fish)

log "done"
