#!/bin/bash

set -euo pipefail

eval $(/opt/homebrew/bin/brew shellenv)

if [ ! -d ~/.fzf ]; then
  git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
fi

~/.fzf/install --all --no-bash --no-zsh
