#!/bin/bash

set -euo pipefail

context='[fzf]'

log() {
  echo "$context $*"
}

log "start"

eval "$(/opt/homebrew/bin/brew shellenv)"

if [ ! -d ~/.fzf ]; then
  git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
fi

fish -c "~/.fzf/install --all --no-bash --no-zsh"

log "finish"
