#!/bin/bash

set -euo pipefail

BASE=$(pwd)

eval $(/opt/homebrew/bin/brew shellenv)

brew install git

GIT_NAME='Sergey Zabolotnov'
GIT_EMAIL='sergey.zabolotnov@gmail.com'

ln -sf $BASE/gitignore ~/.gitignore
ln -sf $BASE/gitconfig ~/.gitconfig

if [ ! -f ~/.gitconfig.user ]; then
  cat << EOF > ~/.gitconfig.user
[user]
  name = $GIT_NAME
  email = $GIT_EMAIL
[includeIf "gitdir:~/projects/"]
  path = ~/projects/.gitconfig
EOF
fi
