#!/bin/bash

set -euo pipefail

context='[git]'

log() {
  echo "$context $*"
}

log "start"

base=$(pwd)

git_name='Sergey Zabolotnov'
git_email='sergey.zabolotnov@gmail.com'

ln -sf $base/gitignore ~/.gitignore
ln -sf $base/gitconfig ~/.gitconfig

if [ ! -f ~/.gitconfig.user ]; then
  cat << EOF > ~/.gitconfig.user
[user]
  name = $git_name
  email = $git_email
[includeIf "gitdir:~/projects/"]
  path = ~/projects/.gitconfig
EOF
fi

log "done"
