#!/bin/bash

set -e

BASE16_DIR=$HOME/.config/base16

mkdir -p $BASE16_DIR
if [ ! -d $BASE16_DIR/fzf ]; then
  git clone https://github.com/nicodebo/base16-fzf.git $BASE16_DIR/fzf
fi
if [ ! -d $BASE16_DIR/shell ]; then
  git clone https://github.com/chriskempson/base16-shell.git $BASE16_DIR/shell
fi

mkdir -p $BASE16_DIR/hooks
cat << EOF > $BASE16_DIR/hooks/fzf
#!/usr/bin/env bash
ln -sf $BASE16_DIR/fzf/fish/base16-\$BASE16_THEME.fish ~/.base16_fzf
fish ~/.base16_fzf
fish -c 'echo \$FZF_DEFAULT_OPTS > $BASE16_DIR/fzf_default_opts'
EOF

chmod +x $BASE16_DIR/hooks/fzf
