#!/bin/bash

BASE=$(pwd)

brew install \
  tmux \
  reattach-to-user-namespace

ln -sf $BASE/tmux.conf ~/.tmux.conf

cat << EOF > ~/.tmux.conf.local
set -g status-bg yellow
set -g status-fg black
EOF
