#!/bin/bash

set -euo pipefail

BASE=$(pwd)

GIT_NAME='Sergey Zaboltonov'
GIT_EMAIL='sergey.zabolotnov@gmail.com'

brew install git || brew upgrade git

ln -sf $BASE/gitignore ~/.gitignore
ln -sf $BASE/gitconfig ~/.gitconfig

if [ ! -f ~/.gitconfig.user ]; then
  cat << EOF > ~/.gitconfig.user
[user]
  name = $GIT_NAME
  email = $GIT_EMAIL
[includeIf "gitdir:~/projects/"]
  path = ~/projects/.gitconfig
EOF
fi
