#!/bin/bash

set -euo pipefail

BASE=$(pwd)

brew install fish || brew upgrade fish

mkdir -p ~/.config/fish
ln -sf $BASE/config.fish ~/.config/fish/config.fish

# Make fish default shell
if [ ! $(grep "fish" /etc/shells) ]; then
  sudo echo "/usr/local/bin/fish" >> /etc/shells
  chsh -s /usr/local/bin/fish
fi

# Install oh-my-fish
if [ ! -d ~/.local/share/omf ]; then
  curl -L https://get.oh-my.fish | fish
fi

if [ ! -f ~/.config.fish.local ]; then
  cat << EOF > ~/.config.fish.local
# Local config
EOF
fi

if [ ! -f ~/.config/fish/functions/fish_prompt.fish ]; then
  cat << EOF > ~/.config/fish/functions/fish_prompt.fish
function fish_prompt
  set_color \$fish_color_cwd
  echo -n (prompt_pwd)

  # k8s namespace
  # if test (string match -r \$HOME (pwd))
    if test -n \$ktlns
      set_color blue
      echo -n " (k8s:\$ktlctx/\$ktlns)"
    end
  # end

  set_color normal

  set -g __fish_git_prompt_showdirtystate 'yes'
  set -g __fish_git_prompt_showcolorhints 'yes'
  set -g __fish_git_prompt_showuntrackedfiles 'yes'
  set -g __fish_git_prompt_color_branch 'yellow'

  echo -n (fish_git_prompt)

  echo -n ' $ '
end
EOF
fi
