#!/bin/bash

brew install fish

ln -sf ~/mydotfiles/config.fish ~/.config/fish/config.fish

# Make fish default shell
if [ ! $(grep "fish" /etc/shells) ]; then
  sudo echo "/usr/local/bin/fish" >> /etc/shells
fi
chsh -s /usr/local/bin/fish

cat << EOF > ~/.config.fish.local
source ~/git/base16-fzf/fish/base16-solarized-light.fish
EOF

if [ ! -d ~/.local/share/omf ]; then
  curl -L https://get.oh-my.fish | fish
fi
