#!/bin/bash

set -euo pipefail

if [ ! -d ~/.asdf ]; then
  git clone https://github.com/asdf-vm/asdf.git ~/.asdf
  cd ~/.asdf && git checkout $(git describe --abbrev=0 --tags)
  mkdir -p ~/.config/fish/completions
  cp ~/.asdf/completions/asdf.fish ~/.config/fish/completions
  cat << EOF > ~/.asdfrc
  legacy_version_file = yes
EOF
fi
