#!/bin/bash

set -euo pipefail

BASE16_DIR=~/.config/base16
FZF_DEFAULT_OPTS_FILE=~/tmp/fzf_default_opts

mkdir -p $BASE16_DIR
if [ ! -d $BASE16_DIR/fzf ]; then
  git clone https://github.com/nicodebo/base16-fzf.git $BASE16_DIR/fzf
fi
if [ ! -d $BASE16_DIR/shell ]; then
  git clone https://github.com/chriskempson/base16-shell.git $BASE16_DIR/shell
fi

mkdir -p $BASE16_DIR/hooks
cat << EOF > $BASE16_DIR/hooks/fzf
#!/usr/bin/env bash

ln -sf $BASE16_DIR/fzf/fish/base16-\$BASE16_THEME.fish ~/.base16_fzf

fish ~/.base16_fzf

fish -c 'echo \$FZF_DEFAULT_OPTS > \$FZF_DEFAULT_OPTS_FILE'
EOF

chmod +x $BASE16_DIR/hooks/fzf
