#!/bin/bash

set -euo pipefail

BASE=$(pwd)

brew install fish || brew upgrade fish

mkdir -p ~/.config/fish
ln -sf $BASE/config.fish ~/.config/fish/config.fish
ln -sf $BASE/fish_plugins ~/.config/fish/fish_plugins

# Make fish default shell
if [ ! $(grep "fish" /etc/shells) ]; then
  sudo echo "/usr/local/bin/fish" >> /etc/shells
  chsh -s /usr/local/bin/fish
fi

if [ ! -f ~/.config.fish.local ]; then
  cat << EOF > ~/.config.fish.local
# Local config
EOF
fi

echo 'Install Fisher (https://github.com/jorgebucaran/fisher)'
fish -c 'curl -sL https://git.io/fisher | source && fisher update'
