#!/bin/bash

BASE=$(pwd)

brew install neovim

# More info: https://github.com/deoplete-plugins/deoplete-jedi/wiki/Setting-up-Python-for-Neovim
pip3 install --user neovim

mkdir -p ~/.config/nvim
ln -sf $BASE/nvimrc ~/.config/nvim/init.vim

if [ ! -d ~/.vim-snippets ]; then
  ln -sf $BASE/vim-snippets ~/.vim-snippets
fi

# About vim-plug: https://github.com/junegunn/vim-plug
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

nvim +PlugInstall +qall

cat << EOF > ~/.vimrc.local
color base16-solarized-light
EOF
