#!/bin/bash

set -euo pipefail

BASE=$(pwd)

function install_or_update {
  local pkg=$1
  brew install $pkg || brew upgrade $pkg
}

which brew || /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

install_or_update "rectangle"
install_or_update "coreutils"
install_or_update "gpg"
install_or_update "direnv"
install_or_update "rg"
install_or_update "translate-shell"
install_or_update "python3"
install_or_update "tree"
install_or_update "htop"
install_or_update "languagetool"
install_or_update "ctags"
install_or_update "jq"
install_or_update "deno"

install_or_update "kitty"
mkdir -p ~/.config/kitty
ln -sf $BASE/kitty.conf ~/.config/kitty/kitty.conf
