#!/bin/bash

set -euo pipefail

if [ ! -d ~/.asdf ]; then
  git clone https://github.com/asdf-vm/asdf.git ~/.asdf
  cd ~/.asdf && git checkout $(git describe --abbrev=0 --tags)
  mkdir -p ~/.config/fish/completions
  cp ~/.asdf/completions/asdf.fish ~/.config/fish/completions
  cat << EOF > ~/.asdfrc
  legacy_version_file = yes
EOF
  fish ~/.asdf/asdf.fish
else
  asdf update
fi

function install() {
  local lang=$1
  local version=$2
  asdf plugin add $lang || asdf plugin update $lang
  asdf install $lang $version
  if [ $version == 'latest' ]; then
    asdf global $lang $(asdf latest $lang)
  else
    asdf global $lang $version
  fi
}

install "ruby" "2.7.2"
gem install neovim

bash -c '${ASDF_DATA_DIR:=$HOME/.asdf}/plugins/nodejs/bin/import-release-team-keyring'
install "nodejs" "latest"
npm install -g neovim
