#!/bin/bash

set -euo pipefail

function install_or_update {
  local pkg=$1
  brew install $pkg || brew upgrade $pkg
}

install_or_update "direnv"
install_or_update "rg"
install_or_update "translate-shell"
install_or_update "python3"
install_or_update "tree"
install_or_update "htop"
install_or_update "languagetool"
