#!/bin/bash

set -euo pipefail

BASE=$(pwd)

brew install neovim || brew upgrade neovim

mkdir -p ~/.config/nvim/lua

ln -sf $BASE/init.vim ~/.config/nvim/init.vim

if [ ! -d ~/.config/nvim/lua/configs ]; then
  ln -sf $BASE/nvim/lua/configs ~/.config/nvim/lua/configs
fi

if [ ! -d ~/.config/nvim/snips ]; then
  ln -sf $BASE/nvim/snips ~/.config/nvim/snips
fi

# About vim-plug: https://github.com/junegunn/vim-plug
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

nvim +PlugInstall +qall
