#!/bin/bash

set -euo pipefail

eval $(/opt/homebrew/bin/brew shellenv)

curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh
$HOME/.cargo/bin/rustup update

if [ ! -d ~/.asdf ]; then
  git clone https://github.com/asdf-vm/asdf.git ~/.asdf
  cd ~/.asdf && git checkout $(git describe --abbrev=0 --tags)
  mkdir -p ~/.config/fish/completions
  cp ~/.asdf/completions/asdf.fish ~/.config/fish/completions
  cat << EOF > ~/.asdfrc
  legacy_version_file = yes
EOF
  source ~/.asdf/asdf.sh
else
  source ~/.asdf/asdf.sh
  asdf update
fi

function install() {
  local lang=$1
  local version=$2
  local repo=${3:-none}

  (if [ $repo == 'none' ]; then
    asdf plugin add $lang
  else
    asdf plugin add $lang $repo
  fi) || asdf plugin update $lang

  asdf install $lang $version

  if [ $version == 'latest' ]; then
    asdf global $lang $(asdf latest $lang)
  else
    asdf global $lang $version
  fi
}

install "ruby" "2.7.2"
install "nodejs" "latest"
install "golang" "latest" "https://github.com/kennyp/asdf-golang.git"
