#!/bin/bash

set -euo pipefail

BASE=$(pwd)

eval $(/opt/homebrew/bin/brew shellenv)

mkdir -p ~/.config/nvim/lua

ln -sf $BASE/init.vim ~/.config/nvim/init.vim

if [ ! -d ~/.config/nvim/lua/configs ]; then
  ln -sf $BASE/nvim/lua/configs ~/.config/nvim/lua/configs
fi

if [ ! -d ~/.config/nvim/snippets ]; then
  ln -sf $BASE/nvim/snippets ~/.config/nvim/snippets
fi

which nvim || brew install neovim

PLUG_VIM=$HOME/.local/share/nvim/site/autoload/plug.vim

if [ ! -f $PLUG_VIM ]; then
  # # About vim-plug: https://github.com/junegunn/vim-plug
  curl -fLo $PLUG_VIM --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

nvim +PlugInstall +qall
