#!/bin/bash

set -euo pipefail

BASE=$(pwd)

eval $(/opt/homebrew/bin/brew shellenv)

mkdir -p ~/.config/nvim/lua

ln -sf $BASE/init.vim ~/.config/nvim/init.vim

if [ ! -d ~/.config/nvim/lua/configs ]; then
  ln -sf $BASE/nvim/lua/configs ~/.config/nvim/lua/configs
fi

if [ ! -d ~/.config/nvim/snippets ]; then
  ln -sf $BASE/nvim/snippets ~/.config/nvim/snippets
fi

# # About vim-plug: https://github.com/junegunn/vim-plug
# curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
#   https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# brew install neovim

# gem install neovim
# npm install -g neovim

# nvim +PlugInstall +qall
