#!/bin/bash

set -euo pipefail

context='[neovim]'

log() {
  echo "$context $*"
}

log "start"

eval "$(/opt/homebrew/bin/brew shellenv)"

base=$(pwd)

mkdir -p ~/.config/nvim/lua

ln -sf $base/plugs.vim ~/.config/nvim/plugs.vim
ln -sf $base/init.vim ~/.config/nvim/init.vim

if [ ! -d ~/.config/nvim/lua/configs ]; then
  ln -sf $base/nvim/lua/configs ~/.config/nvim/lua/configs
fi

if [ ! -d ~/.config/nvim/snippets ]; then
  ln -sf $base/nvim/snippets ~/.config/nvim/snippets
fi

plug_vim=$HOME/.local/share/nvim/site/autoload/plug.vim

if [ ! -f $plug_vim ]; then
  # About vim-plug: https://github.com/junegunn/vim-plug
  curl -fLo $plug_vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

nvim -u ~/.config/nvim/plugs.vim +PlugInstall +qall --headless

log "done"
