#!/bin/bash

set -euo pipefail

BASE=$(pwd)

eval $(/opt/homebrew/bin/brew shellenv)

brew install tmux
brew install reattach-to-user-namespace

ln -sf $BASE/tmux.conf ~/.tmux.conf

cat << EOF > ~/.tmux.conf.local
set -g status-bg black
set -g status-fg white
EOF
