#!/bin/bash

set -euo pipefail

context='[tmux]'

log() {
  echo "$context $*"
}

log "start"

base=$(pwd)

ln -sf $base/tmux.conf ~/.tmux.conf

cat << EOF > ~/.tmux.conf.local
set -g status-bg black
set -g status-fg white
EOF

log "done"
